/*
Copyright 2017 The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// This file was automatically generated by informer-gen

package v1alpha1

import (
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
	inwinstack_v1alpha1 "k8s.io/sample-controller/pkg/apis/inwinstack/v1alpha1"
	versioned "k8s.io/sample-controller/pkg/client/clientset/versioned"
	internalinterfaces "k8s.io/sample-controller/pkg/client/informers/externalversions/internalinterfaces"
	v1alpha1 "k8s.io/sample-controller/pkg/client/listers/samplecontroller/v1alpha1"
	time "time"
)

// EmployeeInformer provides access to a shared informer and lister for
// Employees.
type EmployeeInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() v1alpha1.EmployeeLister
}

type employeeInformer struct {
	factory internalinterfaces.SharedInformerFactory
}

// NewEmployeeInformer constructs a new informer for Employee type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewEmployeeInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options v1.ListOptions) (runtime.Object, error) {
				return client.SamplecontrollerV1alpha1().Employees(namespace).List(options)
			},
			WatchFunc: func(options v1.ListOptions) (watch.Interface, error) {
				return client.SamplecontrollerV1alpha1().Employees(namespace).Watch(options)
			},
		},
		&inwinstack_v1alpha1.Employee{},
		resyncPeriod,
		indexers,
	)
}

func defaultEmployeeInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewEmployeeInformer(client, v1.NamespaceAll, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc})
}

func (f *employeeInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&inwinstack_v1alpha1.Employee{}, defaultEmployeeInformer)
}

func (f *employeeInformer) Lister() v1alpha1.EmployeeLister {
	return v1alpha1.NewEmployeeLister(f.Informer().GetIndexer())
}
