/*
Copyright 2017 The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// This file was automatically generated by informer-gen

package v1beta1

import (
	nutc_v1beta1 "github.com/kairen/worker/pkg/apis/nutc/v1beta1"
	clientset "github.com/kairen/worker/pkg/client/clientset_generated/clientset"
	internalinterfaces "github.com/kairen/worker/pkg/client/informers_generated/externalversions/internalinterfaces"
	v1beta1 "github.com/kairen/worker/pkg/client/listers_generated/nutc/v1beta1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
	time "time"
)

// WorkerInformer provides access to a shared informer and lister for
// Workers.
type WorkerInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() v1beta1.WorkerLister
}

type workerInformer struct {
	factory internalinterfaces.SharedInformerFactory
}

// NewWorkerInformer constructs a new informer for Worker type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewWorkerInformer(client clientset.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options v1.ListOptions) (runtime.Object, error) {
				return client.NutcV1beta1().Workers(namespace).List(options)
			},
			WatchFunc: func(options v1.ListOptions) (watch.Interface, error) {
				return client.NutcV1beta1().Workers(namespace).Watch(options)
			},
		},
		&nutc_v1beta1.Worker{},
		resyncPeriod,
		indexers,
	)
}

func defaultWorkerInformer(client clientset.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewWorkerInformer(client, v1.NamespaceAll, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc})
}

func (f *workerInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&nutc_v1beta1.Worker{}, defaultWorkerInformer)
}

func (f *workerInformer) Lister() v1beta1.WorkerLister {
	return v1beta1.NewWorkerLister(f.Informer().GetIndexer())
}
